# Swagger API config Properties
api:
  description: List of APIs to manage and execute the Task using Polling strategy.
  title: Task Scheduler
  version: 1.0.0
 
# Postgres DB Configuration
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/task_scheduler
    username: task
    password: task
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

## Logging
logging:
  file:  /docker/Certificates/logs/task-scheduler.log
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} - %msg%n'  
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'  
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG
        web: ERROR    
      hibernate: DEBUG 
    com:
      springboot:
        microservice:
          taskscheduler: INFO  


      
      